# All Systems performance

In [1]:
from functions_ml import read_csv_file
performance_path = "performance.csv"

# DoS System

## Binary (DoS (DoS and DDoS) or Benigh)

In [3]:
model_path = ".\\resultats\\DoS\\Binary\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,1.0,1.0,0.999999,1.0,0.999994,0.999961,0.999914,0.999937,0.000002,0.000004,14,32,7389386
1,RF,1.0,1.0,1.000000,1.0,0.999994,0.999973,0.999898,0.999936,0.000001,0.000005,9,38,7389386
0,DT,1.0,1.0,1.000000,1.0,0.999928,0.999445,0.999109,0.999277,0.000027,0.000045,200,330,7389386

## Trinary (DoS or DDoS)(Remove Benigh rows)

In [5]:
model_path = ".\\resultats\\DoS\\Trinary\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,1.0,1.0,1.0,1.0,0.999908,0.999826,0.999877,0.999852,0.000033,0.000059,238,425,7201481
0,DT,1.0,1.0,1.0,1.0,0.999896,0.999811,0.999854,0.999833,0.000041,0.000063,295,453,7201481
1,RF,1.0,1.0,1.0,1.0,0.999860,0.999712,0.999837,0.999774,0.000038,0.000102,276,732,7201481

## All DoS classes

In [2]:
model_path = ".\\resultats\\DoS\\DoS\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,1.0,1.0,1.0,1.0,0.999949,0.999352,0.999805,0.999578,0.000033,0.000018,46,25,1382998
0,DT,1.0,1.0,1.0,1.0,0.999855,0.998459,0.998850,0.998654,0.000083,0.000062,115,86,1382998
1,RF,1.0,1.0,1.0,1.0,0.999846,0.998609,0.999030,0.998819,0.000072,0.000082,100,113,1382998

## All DDoS classes

In [3]:
model_path = ".\\resultats\\DoS\\DDoS\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,1.0,1.0,1.0,1.0,0.999907,0.997951,0.998336,0.998141,0.000051,0.000042,297,244,5818483
0,DT,1.0,1.0,1.0,1.0,0.999755,0.996045,0.995139,0.995588,0.000106,0.000138,619,804,5818483
1,RF,1.0,1.0,1.0,1.0,0.999393,0.993630,0.988402,0.990842,0.000339,0.000268,1972,1560,5818483

# Recon System

## Binary (Recon or Benigh)

In [6]:
model_path = ".\\resultats\\Recon\\Binary\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,0.970008,0.948019,0.969916,0.958356,0.962730,0.936981,0.960772,0.948136,0.009664,0.027606,2915,8327,301637
1,RF,0.999978,0.999972,0.999967,0.999970,0.961053,0.932959,0.960175,0.945599,0.009246,0.029701,2789,8959,301637
0,DT,0.999985,0.999987,0.999972,0.999979,0.944712,0.925524,0.924660,0.925091,0.028010,0.027278,8449,8228,301637

## All Recon classes

In [7]:
model_path = ".\\resultats\\Recon\\All_classes\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,0.934831,0.939892,0.951827,0.945679,0.894860,0.838811,0.907238,0.865206,0.047877,0.057263,3520,4210,73521
1,RF,0.992818,0.993519,0.994348,0.993932,0.880946,0.745639,0.895455,0.768296,0.045701,0.073353,3360,5393,73521
0,DT,0.995183,0.995172,0.996322,0.995744,0.850723,0.808858,0.794835,0.801374,0.076332,0.072945,5612,5363,73521

# Mirai System

## Binary (Mirai or Benigh)

In [8]:
model_path = ".\\resultats\\Mirai\\Binary\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,0.999999,0.999999,0.999998,0.999999,0.999995,0.999993,0.999995,0.999994,0.000003,0.000002,2,1,625629
1,RF,1.000000,1.000000,1.000000,1.000000,0.999994,0.999994,0.999991,0.999992,0.000002,0.000005,1,3,625629
0,DT,1.000000,1.000000,1.000000,1.000000,0.999727,0.999688,0.999654,0.999671,0.000120,0.000153,75,96,625629

## All Mirai classes

In [9]:
model_path = ".\\resultats\\Mirai\\All_classes\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,1.0,1.0,1.0,1.0,0.999894,0.999895,0.999888,0.999892,0.000068,0.000039,30,17,441424
0,DT,1.0,1.0,1.0,1.0,0.999801,0.999800,0.999798,0.999799,0.000116,0.000084,51,37,441424
1,RF,1.0,1.0,1.0,1.0,0.999798,0.999796,0.999793,0.999794,0.000111,0.000091,49,40,441424

# Web System

## Binary (Web or Benigh)

In [10]:
model_path = ".\\resultats\\Web\\Binary\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,0.997142,0.939562,0.993775,0.965022,0.993465,0.879450,0.964835,0.917623,0.001178,0.005358,364,1656,309091
1,RF,1.000000,1.000000,1.000000,1.000000,0.992219,0.832383,0.986275,0.894238,0.000301,0.007480,93,2312,309091
0,DT,1.000000,1.000000,1.000000,1.000000,0.988783,0.870403,0.872141,0.871270,0.005555,0.005662,1717,1750,309091

## All Web classes

In [11]:
model_path = ".\\resultats\\Web\\All_classes\\"
read_csv_file(performance_path, model_path).sort_values(by=['Total rows', 'Accuracy Testing', 'Recall Testing', 'Precision Testing', 'F1 Testing'], ascending=False).head(20)

,Model,Accuracy Training,Recall Training,Precision Training,F1 Training,Accuracy Testing,Recall Testing,Precision Testing,F1 Testing,FU_rate,FL_rate,FU,FL,Total rows
2,XGB,0.999912,0.999932,0.999932,0.999932,0.756483,0.715970,0.746936,0.728137,0.124294,0.119224,858,823,6903
1,RF,1.000000,1.000000,1.000000,1.000000,0.740113,0.686288,0.745134,0.704355,0.126756,0.133131,875,919,6903
0,DT,1.000000,1.000000,1.000000,1.000000,0.714182,0.688415,0.682324,0.685156,0.142836,0.142981,986,987,6903